apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopflow
  labels:
    app: frontend
    version: "1.0"
    part-of: shopflow
    managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: "1.0"
        part-of: shopflow
        managed-by: argocd
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: 535709431171.dkr.ecr.ap-south-1.amazonaws.com/shopflow/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
