apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespace.yaml
  - ../../base/user-svc
  - ../../base/product-svc
  - ../../base/order-svc
  - ../../base/notification-svc

# Staging uses fewer replicas to save cost
patches:
  - target:
      kind: Deployment
      name: user-svc
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: product-svc
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: order-svc
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1