apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-svc
  namespace: shopflow
  labels:
    app: order-svc
    version: "1.0"
    part-of: shopflow
    managed-by: argocd

spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-svc
  template:
    metadata:
      labels:
        app: order-svc
        version: "1.0"
        part-of: shopflow
        managed-by: argo-cd

    spec:
      serviceAccountName: order-sa
      containers:
        - name: order-svc
          image: 535709431171.dkr.ecr.ap-south-1.amazonaws.com/shopflow/order:latest
          imagePullPolicy: Always
          ports:
            containerPort: 8000
          env:
          - name: AWS_REGION
            value: "ap-south-1"

          # Secret Config
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: order-svc-secrets
                key: database_url
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: order-svc-secrets
                key: jwt_secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5    # wait 5s after start before first check
            periodSeconds: 10         # check every 10s
            failureThreshold: 3       # fail 3 times before marking unready

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15   # give app more time to fully start
            periodSeconds: 20
            failureThreshold: 3