# infra/k8s/base/notification-svc/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-sa
  namespace: shopflow
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::156084119771:role/shopflow-notification-svc-role"