# infra/argocd/root-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pranavsoni21/e-commerce-shopflow
    targetRevision: main
    path: infra/argocd        # ← points to the folder with all app yamls
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true